name: nomly
version: '1.0.0'
config-version: 2
profile: nomly
model-paths: [models]
test-paths: [tests]
analysis-paths: [analyses]
clean-targets: [target, logs]

models:
  nomly:
    +meta:
      owner: dispatch
      freshness_class: critical
    +on_table_exists: rename
    +properties:
      format: "'PARQUET'"
      format_version: "2"
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: view
    dispatch:
      +materialized: table
